# Default Database Properties (In memory H2)
spring:
  banner:
    location: banner-default.txt
  h2:
    console:
      enabled: true
      path: /h2 # http://localhost:8080/h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:tasket
    driverClassName: org.h2.Driver
    username: tasket
    password: tasket
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect

---

# Dev Database Properties (local PostgreSQL)
spring:
  banner:
    location: banner-dev.txt
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/tasket
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: P@$$w0rd
---

# Prod Database Properties




