server:
  port: ${PORT:8080}

# Default Database Properties (In memory H2)
---
# Prod Database Properties

spring:
  banner:
    location: banner-prod.txt

  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    liquibase: INFO

---

# Dev Database Properties (local PostgreSQL)
spring:
  banner:
    location: banner-dev.txt
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  config:
    activate:
      on-profile: dev
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/tasket
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
logging:
  level:
    liquibase: INFO
  jpa:
    hibernate:
      ddl-auto: none

---

# Prod Database Properties

spring:
  banner:
    location: banner-prod.txt
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  config:
    activate:
      on-profile: prod
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
   datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    liquibase: INFO


