# Default Database Properties (In memory H2)
spring:
  h2:
    console:
      enabled: true
      path: /h2 # http://localhost:8080/h2 and input the URL and username below (no password required)
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:tasket
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---

# Dev Database Properties (local PostgreSQL )
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/tasket
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: P@$$w0rd
---

# Prod Database Properties

# BANNER
spring.banner.location: classpath:banner.txt


