# Default Database Properties (In memory H2)
spring:
  banner:
    location: banner-default.txt
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2 # http://localhost:8080/h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:tasket
    driverClassName: org.h2.Driver
    username: tasket
    password: tasket
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  config:
    activate:
      on-profile: default
logging:
  level:
    liquibase: INFO

---

# Dev Database Properties (local PostgreSQL)
spring:
  banner:
    location: banner-dev.txt
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  config:
    activate:
      on-profile: dev
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/tasket
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
logging:
  level:
    liquibase: INFO
  jpa:
    hibernate:
      ddl-auto: none

---

# Prod Database Properties




