# Default Database Properties (In memory H2)
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2 # http://localhost:8080/h2 and input the URL and username below (no password required)
#  datasource:
#    url: jdbc:h2:mem:tasket
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect

---

# Dev Database Properties (local PostgreSQL )
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasket
    username: postgres
    password: P@$$w0rd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

---

# Prod Database Properties

# BANNER
spring.banner.location: classpath:banner.txt


